---
# -----------------
# YAML Templates
# -----------------
# Integration tests
_integration-tests: &integration-tests
  os: linux
  language: node_js
  node_js: 12
  services: docker
  cache:
    directories:
      - node_modules
      - plugins/available/kuzzle-plugin-auth-passport-local/node_modules
      - plugins/available/kuzzle-plugin-logger/node_modules
  env: &integration-tests-env
    - DOCKER_COMPOSE_TEST=test
  install:
    - sudo sysctl -w vm.max_map_count=262144
  script:
    # avoid write /dev/stdout: resource temporarily unavailable
    # https://blog.m157q.tw/posts/2018/03/30/travis-ci-stdout-write-error-and-resource-temporarily-unavailable-workaround/
    - python2 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
    - docker-compose -f .ci/$DOCKER_COMPOSE_TEST.yml run kuzzle

# Documentation deployment
_doc-deploy: &doc-deploy
  stage: Deployments
  language: node_js
  node_js: 12
  env: &doc-deploy-env
    - NODE_ENV=production
    - AWS_DEFAULT_REGION=us-west-2
    - AWS_ACCESS_KEY_ID=AKIAIYAXFUAHXOWP2MJA
    # AWS_SECRET_ACCESS_KEY
    - secure: h8n58Siclba6vRZEUcVzH2UTCBaA2src/mJvPaiXln1dPP4+/CICkfoljggA/qZDv9pv1ck07u7fHf6EJa7ONO2aNKD/r9CyyKHbZsgT5Wz6zLaOJfu/DmLZq9yclG/e9XmlK7qpjW+H7vCPn98GNVaU2h8cjqNVZ3KpkLwQ0j2RBoM6x4jpOFUsbiwnKWaHxS2u3JHpZ/L8PM9uy2JDoRm52HW5k+fmvyxwNis+R5ezteJJYcqhYhun9CRDVjGg47t8YFkO+fXjtgl5EAhNlOtE1UixV7h8+MVbmS0XJQm4Xen76J0a2O3xEGOggsdMJebTuDlHk97jhR17pMFu0lfM4V2YmiC8BclY/fdnxX7aoc9hPi9Zf6ReHOqVo8jWP4ArS7awHdKW8c5zkH2itf7M6tw89hnDmoXVk/48joOyj+vMwhvI2wJ3oUjhsjpZWG7Mks4hY2CYmkA5n56K/6+qgPq19qZr4MKqW1zr8066TNzqa2ZtdbtSzIyP0jcXLyNOxhwXejyBnHTyJ7ZVbiNxyGTvLQcOP1UYNn1LxmDTJWvDCguXbwLQ2oHzD032xVuNCS2XjZ1dDFtEtEfDniVnOGosEzJWK2kkRCaOzW5GT+VunfZnN9j4MNZVfI1iCW3EQ4CI7n/Ct89y4YrezwRoFjvMQvhb64pVLwMeOp4=
  cache:
    npm: true
    directories:
      - $HOME/.cache/pip
      - doc/framework/node_modules
  addons:
    apt:
      packages:
        - python
        - python-pip
  install:
    - pip install awscli --upgrade --user
    - npm install --production=false
  script:
    - rm -rf doc/framework
    - npm run doc-prepare && npm run doc-build && npm run doc-upload && npm run doc-cloudfront

# ------------------------
# Jobs configuration
# ------------------------
jobs:
  include:
    # ---------------------------------------
    # Stage: Tests
    # ---------------------------------------
    - name: ESLint - Node 12.16.3
      stage: Tests
      os: linux
      language: node_js
      cache: npm
      node_js: 12.16.3
      install:
        - npm ci --silent
        - npm run build
      script:
        - npm run --silent test:lint

    - name: Unit Tests - Node 12.16.3
      stage: Tests
      os: linux
      language: node_js
      cache: npm
      node_js: 12.16.3
      install:
        - npm ci --silent
        - npm run build
      script:
        - npm run test:unit:coverage
      after_script:
        - npm run codecov

    - name: ESLint - Node 12.18.1
      stage: Tests
      os: linux
      language: node_js
      cache: npm
      node_js: 12.18.1
      install:
        - npm ci --silent
        - npm run build
      script:
        - npm run --silent test:lint

    - name: Unit Tests - Node 12.18.1
      stage: Tests
      os: linux
      language: node_js
      cache: npm
      node_js: 12.18.1
      install:
        - npm ci --silent
        - npm run build
      script:
        - npm run test:unit:coverage
      after_script:
        - npm run codecov

    - name: SonarCloud
      stage: Tests
      if: fork != true
      os: linux
      dist: trusty
      script:
        - .ci/sonar.sh

    - name: Documentation dead links check
      stage: Tests
      language: node_js
      node_js: 12
      cache:
        directories:
          - $HOME/.gem/specs
      install:
        - gem install typhoeus
        - npm ci --silent
      before_script:
        - npm run doc-prepare
        - $(npm bin)/kuzdoc iterate-repos:install --repos_path doc/framework/.repos/
        - $(npm bin)/kuzdoc framework:link -d /core/2/ -v 2
      script:
        - cd doc/framework/
        - HYDRA_MAX_CONCURRENCY=20 ruby .ci/dead-links.rb -p src/core/2/

    - name: Error codes check
      stage: Tests
      language: node_js
      node_js: 12
      install:
        - npm ci --silent
      script:
        - $TRAVIS_BUILD_DIR/.ci/scripts/check-error-codes-documentation.sh

    - name: Functional tests legacy - Node.js 12.16.3
      stage: Tests
      <<: *integration-tests
      env:
        - KUZZLE_FUNCTIONAL_TESTS=test:functional:legacy
        - NODE_VERSION=12.16.3
        - *integration-tests-env

    - name: Functional tests sdk - Node.js 12.16.3
      stage: Tests
      <<: *integration-tests
      env:
        - KUZZLE_FUNCTIONAL_TESTS=test:functional:sdk
        - NODE_VERSION=12.16.3
        - *integration-tests-env

    - name: Functional tests legacy - Node.js 12.18.1
      stage: Tests
      <<: *integration-tests
      env:
        - KUZZLE_FUNCTIONAL_TESTS=test:functional:legacy
        - *integration-tests-env

    - name: Functional tests sdk - Node.js 12.18.1
      stage: Tests
      <<: *integration-tests
      env:
        - KUZZLE_FUNCTIONAL_TESTS=test:functional:sdk
        - *integration-tests-env

    # ---------------------------------------
    # Stage: Cross-platform tests
    # ---------------------------------------
    - <<: *integration-tests
      name: Linux ARMHF
      stage: Cross-platform tests
      env:
        - *integration-tests-env
        - ARM=armhf
        - DOCKER_COMPOSE_TEST=test-$ARM
      before_script:
        - docker run --rm --privileged multiarch/qemu-user-static:register
        - docker run --rm -it -v "$(pwd)":/mnt kuzzleio/sdk-cross:node8-$ARM ./.ci/scripts/install-$ARM-deps.sh

    - <<: *integration-tests
      name: Linux ARM64
      stage: Cross-platform tests
      env:
        - *integration-tests-env
        - ARM=aarch64
        - DOCKER_COMPOSE_TEST=test-$ARM
      before_script:
        - docker run --rm --privileged multiarch/qemu-user-static:register
        - docker run --rm -it -v "$(pwd)":/mnt kuzzleio/sdk-cross:node8-$ARM ./.ci/scripts/install-$ARM-deps.sh

    # ---------------------------------------
    # Stage: Deployments
    # ---------------------------------------
    - name: Dockerhub
      stage: Deployments
      os: linux
      language: node_js
      node_js: 12
      services: docker
      install:
        - npm ci --silent
        - npm run build-ts
      script:
        - MODE=production bash docker/build-docker-images.sh

    - name: Documentation to next-docs.kuzzle.io
      if: branch =~ /^[0-9]+-dev$/
      <<: *doc-deploy
      env:
        - *doc-deploy-env
        - BRANCH=dev
        - S3_BUCKET=docs-next.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E2ZCCEK9GRB49U

    - name: Deploy docs.kuzzle.io
      if: branch =~ /^master|[0-9]+-(stable|beta)$/
      <<: *doc-deploy
      env:
        - *doc-deploy-env
        - S3_BUCKET=docs.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E3D6RP0POLCJMM

    - name: Deploy kuzzle package on NPM
      stage: Deploy latest release on NPM
      if: type = push AND branch =~ /^master|[0-9]+-(stable|beta)$/
      language: node_js
      node_js: 12
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
      before_install:
        - export CC="gcc-4.9" CXX="g++-4.9"
      install:
        - npm install
      script:
        - npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        email: support@kuzzle.io
        tag: latest
        api_key:
          secure: WE+3vUgOvZ2pEKYStsz/9t+VKV7fCYG4ZwC0Xppr4t8M/4EGWa8Pr+cWG4+JuljBYmQry4I4tptfjROR2zNSzGQ0RwwEfvjt/Qbc705qxX2jtF6Dq+sqaha18TfPhjuSSKABSb7NDhzjUdmaJ7ki8DmRsmM/5aqQBHw6TUtHMGejT++jymY3W74SZAHCFw+opsxCrey01UtSTHLussiTP9YntVSwBtNXZ1DQwggZXiPCtPqJcqOOTia8MQt6GA7TLc94drpORKAN7kIShrE7Mg9lpMXT5gDv1cf+9VRyhjZSlPUbBfMN30ZrvPJNboIh31rFLdGLu3WfDG/LHHVzw0aYU9w+RJ63zBlP5DChKWKRgJqqOdW4Z5XT6lImiEQaIICVEN3nCH1uavQICl+O3Z81uEtk4wynRJlbZlfYG0r3vCffiHCeZjj5xy9+XwzpiJysxm+XvIewFiP0jcPjRRl9/un2jQMgeTm6uOMXVnQUgxR3bB5ZAYwKJ3y1rt6pPhKVLXCq1MM6HvaWjBGbLuQbl46OWjG2HNfxTVOqpfovCETrWKKpUUCS3Z+Ho4WUILZs9Jx4HOU02rOcM+gwXN4+WRMKLc1sq6V1gI8D7b/XIDaiDmrdNKSBtlxyfq8wZPcunhSQESHrqbAxquQxD6J8DW4ugjsXXWU89PwT4TY=
        on:
          repo: kuzzleio/kuzzle
          all_branches: true


# ------------------------
# Stages configuration
# ------------------------
stages:
  - name: Tests
    if: type =~ /(cron|pull_request)/ OR (type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/)
  - name: Cross-platform tests
    if: type = cron
  - name: Deployments
    if: type = push AND branch =~ /^master|[0-9]+-(dev|stable|beta)|1-dev|$/

# ---------------------------------------
# Notifications
# ---------------------------------------
notifications:
  slack:
    rooms:
      - secure: nx2W8a0wTPUfMFfR0TQxoA+M0ExUAJxIBy1AfKRlJXHaXN3al+SjLNXDU/OdplN9doae8BhcpHJBLiCDfQFY5Wmmbuxq2wAWhrPduIMPZFttBuxkoWkAbrhzYPsk5t7vERrJbSAynNbKeVL1gj7zitStJxzJzT2Z8y//9KYwXty3hPMJei2R1GCLTIOYp0ddq1Uu02Sdhkg07IO+bCrv5q6NFOpnx27SjYEBIOX66bVnGUcUzrbFQM1WToHwFHU3ylZUbj+zJHu+njj9SNTaoR7nIl6oedHCtloagTxyqjLQ0k3E9O4D5fuVvanKDAnLXrlPHWwNoEjffUMQ/b8OtTpgjB6pTr8Xu5oMN4tb5AbofdFOYIyumhHEN7Yt9t1sI6mYMEPu8GfAUTNHS41QfJakGRjYWOMoWQD4sOwRi8VRx+wOkvGSF75wsIrRM30qOkU4cXjoe44My7OkJKycz5AlvR8Drow5d8FO7N4C8olNM4MyP1Ofs2ulXYVEXEXV9NxuRIpcejx8UUZfBNjHnLsAjgq4sWyey22vTxIlmzc1dN3AngiScNdU7u2emZVBmC9VSLN2hAduA1y7HxESpqxd7+9v8qKxeSYw2j1V1sh2nvOvKah2Y61erDWjOI/eAxQPnT/uF4yoHC3dFnW9j9tCej0vZ0PeIBCUIKb5mx8=
    on_success: never
    on_failure: always
